num1 = int(input("Enter your 1st number: "))
num2 = int(input("Enter your 2nd number: "))
print(f"Subtraction of {num1} and {num2} is {num1 - num2}")
print(f"Addition of {num1} and {num2} is {num1 + num2}")
print(f"multiplication of {num1} and {num2} is {num1 * num2}")
print(f"Division of {num1} and {num2} is {num1 / num2}")
print(f"{num1} // {num2} is {num1 // num2}")
